#data ingestion config
data_source:
  excel_sheet: Source\data\Final.xlsx
  processed_data:
    petrol_vehicle_data: data\processed_data\petrol_data.csv
    electric_vehicle_data: data\processed_data\ev.csv
    price_data: data\processed_data\price.csv

model:
  name: gpt-4.1-nano-2025-04-14